apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-zt-deployment
spec:
   selector:
      matchLabels:
        app: nginx
   template:
      metadata:
        labels:
          app: nginx
      spec:
       containers:
       - name: nginx
         image: nginx:1.7.9
         ports:
         - containerPort: 80
           name: http
       - name: zt-sidecar
         image: zerotier/zerotier-containerized:latest
         ports:
         - name: zt
           containerPort: 9993
         securityContext:
           privileged: true
           capabilities:
             add:
               - NET_ADMIN
               - SYS_ADMIN
         volumeMounts:
           - name: dev-net-tun
             readOnly: true
             mountPath: /dev/net/tun
       volumes:
         - name: dev-net-tun
           hostPath:
             path: /dev/net/tun

---

kind: Service
apiVersion: v1
metadata:
  name: zt-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 9993
    targetPort: 9993
    nodePort: 30100

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

---

kind: Service
apiVersion: v1
metadata:
  name: zt-cluster
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - port: 9993
    targetPort: 9993


