
[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"

[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/viper"
    version="v1.2.0"

[[constraint]]
   name="github.com/onsi/ginkgo"
   version="v1.6.0"

[[constraint]]
    name="github.com/onsi/gomega"
    version="v1.4.2"

[[override]]
   source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
   name = "gopkg.in/fsnotify.v1"

[[constraint]]
    name="k8s.io/client-go"
    version="kubernetes-1.15.5"

[[constraint]]
    name = "k8s.io/api"
    version="kubernetes-1.15.5"

[[override]]
   name = "k8s.io/apimachinery"
   version="kubernetes-1.15.5"

[[override]]
   name = "k8s.io/apiextensions-apiserver"
   version="kubernetes-1.15.5"

[[override]]
   name = "k8s.io/apiserver"
   version="kubernetes-1.15.5"

[[override]]
   name = "k8s.io/cli-runtime"
   version="kubernetes-1.15.5"

# Fix vendor/k8s.io/kubernetes/pkg/kubectl/cmd/templates/markdown.go:30:5: cannot use ASCIIRenderer literal (type *ASCIIRenderer) as type blackfriday.Renderer in assignment:
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

# Fix vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"


[[constraint]]
    name="github.com/nalej/grpc-utils"
    version="=v1.5.0"

[[constraint]]
    name = "github.com/nalej/grpc-conductor-go"
    version="=v0.0.96"


[[constraint]]
    name = "github.com/nalej/grpc-application-go"
    version="=v0.0.87"

[[constraint]]
    name = "github.com/nalej/grpc-deployment-manager-go"
    version="=v0.0.64"

[[constraint]]
    name = "github.com/nalej/grpc-cluster-api-go"
    version="=v0.0.24"

[[constraint]]
    name = "github.com/nalej/grpc-network-go"
    version="=v0.0.45"

[[constraint]]
    name = "github.com/nalej/grpc-installer-go"
    version="=v0.0.35"

[[constraint]]
    name = "github.com/nalej/grpc-zt-nalej-go"
    version="=v0.0.4"

[[constraint]]
    name = "github.com/prometheus/client_golang"
    version = "=v0.9.2"

[[constraint]]
    name = "istio.io/client-go"
    version = "=1.4.0"