kind: Service
apiVersion: v1
metadata:
  name: deployment-manager
  labels:
    cluster: application
    component: deployment-manager
  namespace: nalej
spec:
  selector:
    cluster: application
    component: deployment-manager
  type: NodePort
  ports:
  - protocol: TCP
    port: 5200
    targetPort: 5200