kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: application
    component: deployment-manager
  name: deployment-manager
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: application
      component: deployment-manager
  template:
    metadata:
      labels:
        cluster: application
        component: deployment-manager
    spec:
      containers:
      - name: deployment-manager
        image: nalej/deployment-manager:VERSION
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 2000
        args:
        - "run"
        - "--local"
        - "-d deployment-manager.nalej:5200"
        env:
        - name: MANAGER_CLUSTER_IP
          valueFrom:
            secretKeyRef:
              name: manager-cluster-secret
              key: MANAGER_CLUSTER_IP
        - name: MANAGER_CLUSTER_PORT
          valueFrom:
            secretKeyRef:
              name: manager-cluster-secret
              key: MANAGER_CLUSTER_PORT
        ports:
        - name: api-port
          containerPort: 5200
