kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: application
    component: deployment-manager
  name: deployment-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: application
      component: deployment-manager
  template:
    metadata:
      labels:
        cluster: application
        component: deployment-manager
    spec:
      serviceAccountName: deployment-manager
      containers:
      - name: deployment-manager
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/deployment-manager:__NPH_VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        args:
        - "run"
        - "--local"
        - "--depMgrAddress=$(DEPLOYMENT_MANAGER_SERVICE_HOST):5200"
        - "--clusterAPIHostname=$(CLUSTER_API_HOST)"
        - "--clusterAPIPort=443"
        - "--useTLSForClusterAPI=true"
        - "--loginHostname=$(LOGIN_API_HOST)"
        - "--loginPort=443"
        - "--useTLSForLogin=true"
        - "--clusterPublicHostname=$(CLUSTER_PUBLIC_HOSTNAME)"
        - "--email=$(EMAIL)"
        - "--password=$(PASSWORD)"
        - "--dns=$(DNS_HOSTS)"
        - "--planetPath=/zt/planet/planet"
        - "--publicRegistryUserName=$(PUBLIC_REGISTRY_USERNAME)"
        - "--publicRegistryPassword=$(PUBLIC_REGISTRY_PASSWORD)"
        - "--publicRegistryURL=$(PUBLIC_REGISTRY_URL)"
        - "--debug"
        env:
        - name: MANAGER_CLUSTER_IP
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: management_public_host
        - name: MANAGER_CLUSTER_PORT
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: management_public_port
        - name: CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: cluster_id
        - name: CLUSTER_API_HOST
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: cluster_api_hostname
        - name: LOGIN_API_HOST
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: login_api_hostname
        - name: CLUSTER_PUBLIC_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: cluster_public_hostname
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: cluster-user-credentials
              key: email
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-user-credentials
              key: password
        - name: DNS_HOSTS
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: dns_public_ips
        - name: PUBLIC_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-public-registry
              optional: true
              key: username
        - name: PUBLIC_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-public-registry
              optional: true
              key: password
        - name: PUBLIC_REGISTRY_URL
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-public-registry
              optional: true
              key: url
        ports:
        - name: api-port
          containerPort: 5200
        volumeMounts:
          - name: zt-planet
            mountPath: /zt/planet
            readOnly: true
      imagePullSecrets:
      - name: nalej-registry
      volumes:
        - name: zt-planet
          secret:
            secretName: zt-planet
