kind: Service
apiVersion: v1
metadata:
  name: deployment-manager
  namespace: __NPH_NAMESPACE
  labels:
    cluster: application
    component: deployment-manager
spec:
  selector:
    cluster: application
    component: deployment-manager
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5200
    targetPort: 5200
  - protocol: TCP
    port: 5201
    targetPort: 5201
    name: metrics
