apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    cluster: application
    component: deployment-manager
  name: deployment-manager
  namespace: __NPH_NAMESPACE
spec:
  endpoints:
  - interval: 60s
    port: metrics
  jobLabel: component
  selector:
    matchLabels:
      component: deployment-manager
